### ISSUE TITLE
执行没有任何输出

### ISSUE THREAD

**Issue by lguiwind** [ifacker/WIHscan#2]
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/7a9f1b49-40e4-4e19-807f-056eb95ba153">

**Comment by ifacker** [comment]
没有结果应该是规则没有匹配到，可以去HaE最新版里扒一些规则出来，如果你的js.txt是ARL的WIH扫描结果的话，ARL里有一些是匹配的域名，域名在默认规则里是没有开启的，如果你需要的话，可以开启一下。
